//
//  StickerPickerSheet.swift
//  Aura iOS
//

import SwiftUI

/// The set of sticker assets an avatar can be set to — the general method
/// stickers plus the habit foxes. (App-brand icons and the exercise/camera-rep
/// stickers are intentionally excluded.)
enum StickerCatalog {
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    /// GENERATED by tools/install_stickers.py — do not hand-edit.
    /// Derived from the asset catalogue so it cannot fall behind the art.
    static let all: [String] = [
        "AuraCoinIcon", "EarnCardIcon", "ScrollCardIcon", "StreakFireIcon",
        "FoxPhotoProof", "FoxCameraReps", "FoxDeepFocus", "FoxAppleHealth",
        "FoxHabitBrushTeeth", "FoxHabitCleanRoom", "FoxHabitDeepWork", "FoxHabitGardening",
        "FoxHabitGym", "FoxHabitHealthyMeal", "FoxHabitHydrate", "FoxHabitJournal",
        "FoxHabitMakeBed", "FoxHabitMeditate", "FoxHabitPracticeInstrument", "FoxHabitRead",
        "FoxHabitRun", "FoxHabitSkincare", "FoxHabitSmile", "FoxHabitSocialize",
        "FoxHabitStudy", "FoxHabitTakeVitamins", "FoxHabitTouchGrass", "FoxHabitWalk",
        "FoxHabitWorkOnBusiness", "FoxHabitYoga", "FoxCaloriesBurned", "FoxCreateRoutine",
        "FoxExerciseMinutes", "FoxLockInRoutine",
        "FoxMindfulMinutes", "FoxRunWalk", "FoxSettingsBugReport",
        "FoxSettingsContact", "FoxSettingsDifficulty", "FoxSettingsGear", "FoxSettingsHelp",
        "FoxSettingsName", "FoxSettingsReminders",
        "FoxSteps",
    ]
}

/// A grid sticker picker — same sheet chrome/size as the Target Time and App
/// Lists sheets (drag capsule + centered title + X, `.height(420)` detent). The
/// current selection carries a blue border + a faint blue wash.
struct StickerPickerSheet: View {
    @Environment(\.dismiss) private var dismiss

    let selected: String?
    var onSelect: (String?) -> Void

    /// Local mirror so tapping a sticker highlights it without dismissing — the
    /// user closes the sheet manually.
    @State private var localSelected: String?

    init(selected: String?, onSelect: @escaping (String?) -> Void) {
        self.selected = selected
        self.onSelect = onSelect
        _localSelected = State(initialValue: selected)
    }


    private let columns = Array(repeating: GridItem(.flexible(), spacing: Theme.Spacing.m), count: 4)

    var body: some View {
        VStack(spacing: 0) {
            header

            ScrollView(showsIndicators: false) {
                LazyVGrid(columns: columns, spacing: Theme.Spacing.m) {
                    ForEach(StickerCatalog.all, id: \.self) { name in
                        cell(name)
                    }
                }
                .padding(.horizontal, Theme.Spacing.xl)
                .padding(.top, Theme.Spacing.s)
                .padding(.bottom, Theme.Spacing.xxl)
            }
        }
        .background(LightSheet.bg.ignoresSafeArea())
        .presentationDetents([.height(420)])
        .presentationDragIndicator(.hidden)
    }

    private var header: some View {
        VStack(spacing: 0) {
            LightDragCapsule()

            Text("Choose a Sticker")
                .auraFont(.display, 22, .bold)
                .foregroundStyle(LightSheet.title)
                .frame(maxWidth: .infinity)
            .padding(.horizontal, Theme.Spacing.xl)
            .padding(.top, Theme.Spacing.l)
            .padding(.bottom, Theme.Spacing.l)
        }
    }

    private func cell(_ name: String) -> some View {
        let isSelected = localSelected == name
        return Button {
            localSelected = name
            onSelect(name)
        } label: {
            Image(name)
                .resizable()
                .interpolation(.high)
                .scaledToFit()
                .frame(width: 46, height: 46)
                .frame(maxWidth: .infinity)
                .frame(height: 72)
                .background(isSelected ? LightSheet.blueWash : LightSheet.field,
                           in: RoundedRectangle(cornerRadius: Theme.Radius.field, style: .continuous))
                .overlay(
                    RoundedRectangle(cornerRadius: Theme.Radius.field, style: .continuous)
                        .strokeBorder(isSelected ? LightSheet.blue : Color.clear, lineWidth: 2)
                )
        }
        .buttonStyle(PressBounceStyle())
    }
}

#Preview {
    Color.gray.sheet(isPresented: .constant(true)) {
        StickerPickerSheet(selected: "FoxDeepFocus") { _ in }
    }
}
